# Setup
title:               Wyatt Walsh 
tagline:            
description:         
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wyatt Walsh
  url:               
  email:             wyattowalsh@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote-theme: poole/lanyon