# Setup
title:              Wyatt Walsh
tagline:            Reach out, let's build some cool stuff! 
description:         
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wyatt Walsh
  url:               wwalsh.io
  email:             wyattowalsh@gmail.com
  github:            wyattowalsh
  twitter:           wyattowalsh
  linkedin:          wyattowalsh
  spotify:           wyattowalsh
  stack-overflow:     wyattowalsh
  kaggle:            wyattowalsh
  medium:            wyattowalsh
  bio: BS in Industrial Engineering and Operations Research from UC Berkeley

# Gems
plugins:
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-google-photos

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote-theme: poole/lanyon

collections:
  - medium_posts