# Setup
title:              Wyatt Walsh
tagline:            Reach out, let's build some cool stuff! 
description:        Personal website of Wyatt Walsh. Here, you can find more information about me, see my blog writings, view my data science notes, or see examples of my favorite media.
url:                https://wwalsh.io/
logo:               /public/favicon/favicon-32x32.png
baseurl:             ''
paginate:            5
permalink:           pretty
social:
  name: Wyatt Walsh
  links:
    - https://twitter.com/wyattowalsh
    - https://www.linkedin.com/in/wyattowalsh
    - https://github.com/wyattowalsh
    - https://medium.com/@wyattowalsh
    - https://www.kaggle.com/wyattowalsh
    - 
# About/contact
author:
  name:              Wyatt Walsh
  url:               wwalsh.io
  email:             wyattowalsh@gmail.com
  github:            wyattowalsh
  twitter:           wyattowalsh
  linkedin:          wyattowalsh
  spotify:           wyattowalsh
  stack-overflow:    wyattowalsh
  kaggle:            wyattowalsh
  medium:            wyattowalsh
  bio: BS in Industrial Engineering and Operations Research from UC Berkeley

# Gems
plugins:
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-google-photos
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-twitter-plugin 

# Custom vars
version:             1.1.0
google_analytics_id: G-FJCYWXT2WF

remote-theme: poole/lanyon

collections:
  - medium_posts

last-modified-at:
    date-format: 'Last modified: %d-%b-%y'