# Setup
title:               Wyatt Walsh 
tagline:            
description:         
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wyatt Walsh
  url:               wwalsh.io
  email:             wyattowalsh@gmail.com
  github: wyattowalsh
  twitter: wyattowalsh
  linkedin: wyattowalsh
  spotify: wyattowalsh
  # google_analytics_id: UA-27104497-1
  # google_analytics_url: patricksteadman.ca
  bio: BS in Industrial Engineering and Operations Research from UC Berkeley

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

remote-theme: poole/lanyon

collections:
  - medium_posts